### ISSUE TITLE
Paper link 404

### ISSUE THREAD

**Issue by mdavidsaver** [BerkeleyLab/Zest#5]
The CERN [link](http://accelconf.web.cern.ch/AccelConf/napac2016/papers/tupoa40.pdf) in the README now returns a 404.

https://github.com/BerkeleyLab/Zest/blob/43e8c67fba8082a3a21e5eda8ba646df3bf2c3b9/README.md?plain=1#L75C1-L77C80

**Comment by mdavidsaver** [comment]
I found what I think is a new URL.  Is this the same paper?

https://accelconf.web.cern.ch/napac2016/papers/tupoa40.pdf

**Comment by ldoolitt** [comment]
Yes.
`31e12ff99218b0af442ee49b99f9bdd18fad4b6ffb2036ee2ae2193ea4c42ac5  tupoa40.pdf`

**Comment by ldoolitt** [comment]
@mdavidsaver thanks for pointing this out!  Fixed.

**Comment by mdavidsaver** [comment]
You might want to add this citation to the README for the [gitlab](https://gitlab.com/lbl-boards/zest) project as well.
